<?php
declare(strict_types=1);
use App\Tutorials\Class4\Admin\User as AdminUser;
use App\Tutorials\Class4\User;
// Composer's loader registers a callback for PSR-4 and other autoloading rules
// Commonly called the Composer bootstrap file, it is generated by Composer and should not be edited
require_once __DIR__ . '/../../vendor/autoload.php';
echo (new User('Avery'))->getName(), '<br>', PHP_EOL;
echo (new AdminUser('Morgan'))->getName(), '<br>', PHP_EOL;